os: osx
osx_image: xcode9.3
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  bundler: true
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
  - "$HOME/Library/Caches/Homebrew"
env:
  global:
  - TERM=dumb
  - ANDROID_HOME=/usr/local/share/android-sdk
  - MONO_URL="https://download.mono-project.com/archive/5.12.0/macos-10-universal/MonoFramework-MDK-5.12.0.226.macos10.xamarin.universal.pkg"
  - UNITY_URL="https://download.unity3d.com/download_unity/21ae32b5a9cb/MacEditorInstaller/Unity-2017.4.3f1.pkg"
install:
- brew tap caskroom/cask
- brew cask install android-sdk
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager --licenses
- curl -o Mono.pkg $MONO_URL & curl -o Unity.pkg $UNITY_URL & wait
- sudo installer -dumplog -package Mono.pkg -target /
- export PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/Commands"
- sudo installer -dumplog -package Unity.pkg -target /
- bundle install
script: bundle exec rake
deploy:
  provider: releases
  api_key:
    secure: gSy4ckptDBnexHVmlSiSukVMu3VmaTAwGwuR6HzMgw2qSPuZ76A9g1ta+gc6bpaSyodwtl4BRwDB9QQtj5qmGdWxWK6xHQ9FQXfksU8p8fuhactkv78igFHmdXg1Hih+0Qep2Kl5vOZ4rBvPMT8VjidYu3VYqBgEL87atTBCTG4=
  file: Bugsnag.unitypackage
  draft: true
  on:
    tags: true
    repo: bugsnag/bugsnag-unity
