steps:
  - label: Build something
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    commands:
      - bundle exec rake plugin:export
      - bundle exec bugsnag-maze-runner
    concurrency: 2
    concurrency_group: 'unity-license'
