steps:
  - label: Build and run e2e tests for Unity 5.6.7f1
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "5.6.7f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
      - bundle exec bugsnag-maze-runner
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: Build and run e2e tests for Unity 2017.4.40f1
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2017.4.40f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
      - bundle exec bugsnag-maze-runner
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage
    concurrency: 2
    concurrency_group: 'unity-license'

  - label: Build and run e2e tests for Unity 2018.4.34f1
    timeout_in_minutes: 30
    agents:
      queue: opensource-mac-unity
    env:
      UNITY_VERSION: "2018.4.34f1"
    commands:
      - bundle install
      - bundle exec rake plugin:export
      - bundle exec bugsnag-maze-runner
    artifact_paths:
      - Bugsnag.unitypackage
      - Bugsnag-with-android-64bit.unitypackage
    concurrency: 2
    concurrency_group: 'unity-license'
